Translated 3.1/usingthymeleaf.md into Japanese
thymeleaf-docs-ja/thymeleaf-docs pull request #19
Opened 2023-01-03 08:36 UTC by MasatoshiTada

- 3.0/usingthymeleaf.mdと3.1/usingthymeleaf.mdのdiffを確認して、差分がある箇所のみ翻訳を追加・変更・削除しました。
  - 差分の無い箇所の翻訳は一切変更していません。
- thymeleaf31whatsnew.mdは新規に翻訳しました。

2023-03-04 04:45 UTC, bufferings commented
遅くなってしまってすみません。ありがとうございます。確認します。

ひとつお伺いしておきたいのですが
usingthymeleafは翻訳版を公式サイトに載せてもらうとして、whatsnewはどのように利用する予定でしょうか？このリポジトリは日本語サイト用のリポジトリというわけではないので、もしかしたらこのリポジトリで翻訳するよりは @MasatoshiTada さんがご自身のブログなどで公開される方が、日本のThymeleafユーザーのみなさんにとってはいいかもしれません。ご意見をお伺いしたいです。

2023-03-04 05:15 UTC, bufferings commented
（ごにょごにょして、3.0->3.1の差分だけが見えるようにしました）

2023-03-04 05:48 UTC, MasatoshiTada commented
> usingthymeleafは翻訳版を公式サイトに載せてもらうとして、whatsnewはどのように利用する予定でしょうか？このリポジトリは日本語サイト用のリポジトリというわけではないので公開先がありません。もしかしたらこのリポジトリで翻訳するよりは @MasatoshiTada さんがご自身のブログなどで公開される方が、日本のThymeleafユーザーのみなさんにとってはいいかもしれません。ご意見をお伺いしたいです
。

whatsnewの方はどうしようかなあ・・・と悩んでいました。
公式サイトの👇のあたりに掲載していただけたらそれでいいし、僕個人のブログに掲載できるのであればそれでもいいかなと思っています。

<img width="1002" alt="スクリーンショット 2023-03-04 14 46 00" src="https://user-images.githubusercontent.com/7044137/222878404-f3c26b36-c442-48d5-9dad-c0fd05777bf4.png">

Danielさんに相談して決めたほうがいいでしょうか？

2023-03-04 06:42 UTC, bufferings commented
なるほどです。僕はどちらでも構わないので、お任せします！公式サイトにのせるならDanielに相談してみてください。のせることになったら、whatsnewの内容もレビューしますね。たださんのブログで書くことにするなら、自分のレビューは不要だと思います！

2023-03-04 07:21 UTC, MasatoshiTada commented
了解です！ではDanielさんに相談してみます。
まずはusingthymeleafのほうのレビューをお願いします！

2023-03-04 15:59 UTC, bufferings reviewed
usingthymeleafをレビューしました。自分の意見、というだけですので、これが正解というわけではないです。ご意見をお伺いしたいです。

細かい部分ですが日本語の文章の中では

* 括弧、コロンなどは全角
* 基本的には`` `foobar` ``や`*foobar*`の周りにスペースを入れない
* Web→ウェブ

かなと思います。

whatsnewはDanielとのやりとりに時間が多少かかるんじゃないかと思うので、別のPRに分けたほうがいいかもしれません。

また、3.1対応をするのであれば、私たちが日本語版ドキュメントを出した後に3.0に入った修正も反映させる必要があると思うので、このPRのレビューが終わったら、その作業もしなきゃですね。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリは2つの(同じ)バージョンがあります:
他の場所は前後にスペース入れてなさそう？

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリは2つの(同じ)バージョンがあります:
> このアプリは2つの(同じ)バージョンがあります

* このアプリ「に」は

括弧は全角

* 2つの（同じ）バージョン

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリは2つの(同じ)バージョンがあります:
こうかな？

```suggestion
この章以降で使用しているサンプルのソースコードは*Good Thymes Virtual Grocery (GTVG)*サンプルアプリにあります。このアプリには2つの（同じ）バージョンがあります:
```

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +* `javax.*` ベース: [gtvg-javax](https://github.com/thymeleaf/thymeleaf/tree/3.1-master/examples/core/thymeleaf-examples-gtvg-javax).
* 英語版だと、アスタリスクの前にスペースが入っているので、揃えたほうがいいのかな？
* `` `javax.*` `` や `` `jakarta.*` `` の周りにもスペースは不要かと
* コロンは全角

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +        final IWebExchange webExchange =
@MasatoshiTada さんが見た後に追加されたのかもしれないんですけど、このメソッドの直前にinitメソッドが追加されているので、対応をお願いしたいです！Javadocの翻訳も合わせて。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +            ControllerMappings.resolveControllerForRequest(webRequest);
英語版だと、この後に、↓のdiffもあるのでご確認お願いします。

```diff
-        /*
-         * Obtain the TemplateEngine instance.
-         */
-        ITemplateEngine templateEngine = this.application.getTemplateEngine();
-
```

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +         * Obtain the response writer
翻訳してほしいな

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +`org.thymeleaf.TemplateEngine` がどのように初期化されるかを見てみましょう:
* スペース不要
* コロンは全角

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // Templates will be resolved as application (ServletContext) resources
英語は残さなくていいと思います。消し忘れかな。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // テンプレートはアプリケーション(ServletContext)リソースとして解釈されます
括弧は全角

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // テンプレートのキャッシュTTLを1時間に設定します。
```suggestion
    // テンプレートキャッシュのTTLを1時間に設定します。
```

のほうが好きかな。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // 設定しなかった場合、エントリはLRUによって追放されるまで保持されます
```suggestion
    // 未設定の場合、エントリーはLRUで追い出されるまで保持されます
```

好みだけです。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> -
英語版だと空白行が2行あるので、この改行は消さなくてもいいんじゃないかと思います。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    public IWebExchange getExchange();
英語版だと、これの少し上の部分にも変更が入っているようです

```diff
There is a specialized extension of this interface, `org.thymeleaf.context.IWebContext`,
-meant to be used in ServletAPI-based web applications (like SpringMVC).
+meant to be used in web applications.
```

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
>  WebContext ctx = new WebContext(request, response, servletContext, request.getLocale());
英語版だと、ここにも変更が入っています。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * `${x}`はThymeleafのコンテキストや*エクスチェンジ属性*に保持されている変数`x`を返します(サーブレット用語では*リクエスト属性*)。
括弧は全角で

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * `${application.x}`は`x`という名前の*アプリケーション属性*を返します(サーブレット用語では*サーブレットコンテキスト属性*)。
括弧は全角で

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    final IWebExchange webExchange,
ここから`throws Exception {`まで、英語版とインデントが異なります。特に理由がなければ、英語版に揃えたほうが良いんじゃないかと思います。理由があるなら知りたいですー！

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +グッドタイムス仮想食料品店では`ITemplateResolver`実装の`WebApplicationTemplateResolver`を選んだので、テンプレートをアプリケーションリソース(サーブレットベースWebアプリにおける*サーブレットコンテキスト*)からリソースとして取得しています。
* 括弧は全角で
* 「Webアプリ」は他と合わせてカタカナで「ウェブアプリ」
* 「サーブレットベースウェブアプリ」よりも「サーブレットベースのウェブアプリ」のように「の」を入れるほうが読みやすいかなと思う。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 標準ロケールの形式で日付をフォーマットします
> 標準ロケールの形式

カレンダーと合わせて「標準ロケールフォーマット」でいいかなと思います。

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 指定されたロケールの標準形式で日付をフォーマットします
「標準形式」→「標準フォーマット」

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * SHORT、MEDIUM、LONG、FULLを指定してjava.time.format.FormatStyleのデフォルトのパターンを指定することもできます
「指定して〜指定する」と二重になっているので、少し意訳ですがこんな感じだと意味が分かりやすいかな？

```suggestion
 * SHORT、MEDIUM、LONG、FULLを指定すると、java.time.format.FormatStyleのパターンが適用されます
```

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * Format date with ISO-8601 format
翻訳漏れかな

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 日付プロパティを取得します
日付「の」プロパティ

かな

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +* **\#temporals** : JDK8以上の `java.time` APIの日付/時間オブジェクトを処理します:
* `java.time`前後の空白不要
* 「deal with」は「扱います」のほうが自然かな

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 構成要素からtemporal(java.time.Temporal)オブジェクトを作成します
括弧は全角

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 現在日時からtemporal(java.time.Temporal)オブジェクトを作成します
括弧は全角

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 指定された日付からtemporal(java.time.Temporal)オブジェクトを作成します
括弧は全角

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +テンプレートリゾルバーは、どのようにテンプレートにアクセスするかを決める役割を担っています。GTVGアプリケーションでは`org.thymeleaf.templateresolver.WebApplicationTemplateResolver`を使用しているので*IWebApplication*からテンプレートファイルをリソースとして取得する、ということになります：これはサーブレットベースのア
正確には「*IWebApplication*から」じゃなくて「*IWebApplication*オブジェクトから」かな。インターフェースに対してオブジェクトと呼ぶのは少し変な気もしますが、原文を尊重して「オブジェクト」を入れておいたらいいかなと思います。

それと、少し日本語が不自然なので、こんな感じでどうかな？

```suggestion
テンプレートリゾルバーは、どのようにテンプレートにアクセスするかを決める役割を担っています。GTVGアプリケーションでは`org.thymeleaf.templateresolver.WebApplicationTemplateResolver`を使用しているので、*IWebApplication*オブジェクトからテンプレートファイルをリソースとして取得する、ということになります：*IWebApplication*はThymeleafが抽象化したもので、ウェブアプリケーションルートからリソースを解決します。サーブレットベースのアプリケーションの場合は、基本的にはサーブレットAPIの`[javax|jakarta].servlet.ServletContext`オブジェクトをラップしたものになります。
```

2023-03-04 15:59 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +`WebContext`コンストラクタは、Webベース通信（すなわちリクエストとレスポンス）を表すフィルターで作られた`IWebExchange`抽象オブジェクトに含まれる情報を必要とします。ロケールに何も指定しなければシステムのデフォルトロケールが使用されます（実際のアプリケーションでは絶対に指定した方が良いですが）。
Web→ウェブ、がいいかな。

それと、ちょっと内容が違う気がします。こうかな？

```suggestion
`WebContext`コンストラクタは、`IWebExchange`抽象オブジェクトに含まれる情報を必要とします。`IWebExchange`抽象オブジェクトはウェブベースの通信（すなわちリクエストとレスポンス）を表しており、フィルターで生成されています。ロケールに何も指定しなければシステムのデフォルトロケールが使用されます（実際のアプリケーションでは絶対に指定した方が良いですが）。
```

2023-03-05 00:15 UTC, MasatoshiTada commented
詳細なレビューありがとうございますー😊
ちょっとずつ対応していきますので、少々お待ちください〜

2023-03-05 00:17 UTC, MasatoshiTada commented
whatsnewのほうは、Danielさんにメールして今は返信待ちの状態です。

2023-03-12 05:43 UTC, MasatoshiTada commented
Danielさんから返信が来ないです…😅
Twitterでメンションしたんですけど、そっちも反応ナシです。

2023-03-13 07:39 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +        final IWebExchange webExchange =
あらら、ホントだ😅
翻訳追加します！

2023-03-13 07:59 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +            ControllerMappings.resolveControllerForRequest(webRequest);
削除しました！

2023-03-13 07:59 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +         * Obtain the response writer
翻訳しました💪

2023-03-13 08:00 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +* `javax.*` ベース: [gtvg-javax](https://github.com/thymeleaf/thymeleaf/tree/3.1-master/examples/core/thymeleaf-examples-gtvg-javax).
対応しました！

2023-03-13 08:00 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリは2つの(同じ)バージョンがあります:
修正しました！

2023-03-13 08:01 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +`org.thymeleaf.TemplateEngine` がどのように初期化されるかを見てみましょう:
修正しました！

2023-03-13 08:02 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // Templates will be resolved as application (ServletContext) resources
消し忘れですね😅
削除しましたー！

2023-03-13 08:02 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // テンプレートはアプリケーション(ServletContext)リソースとして解釈されます
修正しました！

2023-03-13 08:03 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // テンプレートのキャッシュTTLを1時間に設定します。
修正しました！

2023-03-13 08:04 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // 設定しなかった場合、エントリはLRUによって追放されるまで保持されます
確かに「追放」ってキツイ表現ですね😅
修正しました！

2023-03-13 08:05 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> -
改行を復活させました！

2023-03-13 08:07 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    public IWebExchange getExchange();
「Webアプリケーションで使用されることを想定して作られた」に修正しました！

2023-03-13 08:12 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
>  WebContext ctx = new WebContext(request, response, servletContext, request.getLocale());
コードの部分ですね！修正しました〜

2023-03-13 08:13 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * `${x}`はThymeleafのコンテキストや*エクスチェンジ属性*に保持されている変数`x`を返します(サーブレット用語では*リクエスト属性*)。
修正しました！

2023-03-13 08:13 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * `${application.x}`は`x`という名前の*アプリケーション属性*を返します(サーブレット用語では*サーブレットコンテキスト属性*)。
修正しました！

2023-03-13 08:15 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    final IWebExchange webExchange,
あらら、単にコピペ時にIntelliJさんが勝手にやってくれたものだと思います😅
英語版に合わせて修正しましたー！

2023-03-13 08:16 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +グッドタイムス仮想食料品店では`ITemplateResolver`実装の`WebApplicationTemplateResolver`を選んだので、テンプレートをアプリケーションリソース(サーブレットベースWebアプリにおける*サーブレットコンテキスト*)からリソースとして取得しています。
修正しました！

2023-03-13 08:17 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 標準ロケールの形式で日付をフォーマットします
修正しました！

2023-03-13 08:17 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 指定されたロケールの標準形式で日付をフォーマットします
修正しました！

2023-03-13 08:24 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * SHORT、MEDIUM、LONG、FULLを指定してjava.time.format.FormatStyleのデフォルトのパターンを指定することもできます
あらら、ホントだ😅
2つ目の「指定」を「利用」に変えて `SHORT、MEDIUM、LONG、FULLを指定してjava.time.format.FormatStyleのデフォルトのパターンを利用することもできます` でもイイかなーと思ったんですが、ちょっと長いですね・・・。
椎葉さんの案だと、短くまとまってて良いですねー。その案、いただきます！

2023-03-13 08:27 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * Format date with ISO-8601 format
翻訳しましたー！

2023-03-13 08:28 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 日付プロパティを取得します
修正しました！

2023-03-13 08:30 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +* **\#temporals** : JDK8以上の `java.time` APIの日付/時間オブジェクトを処理します:
修正しました！あと、コロンが半角だったので全角にしました。

2023-03-13 08:31 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 構成要素からtemporal(java.time.Temporal)オブジェクトを作成します
修正しました！

2023-03-13 08:31 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 現在日時からtemporal(java.time.Temporal)オブジェクトを作成します
修正しました！

2023-03-13 08:31 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 指定された日付からtemporal(java.time.Temporal)オブジェクトを作成します
修正しました！

2023-03-13 08:36 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +テンプレートリゾルバーは、どのようにテンプレートにアクセスするかを決める役割を担っています。GTVGアプリケーションでは`org.thymeleaf.templateresolver.WebApplicationTemplateResolver`を使用しているので*IWebApplication*からテンプレートファイルをリソースとして取得する、ということになります：これはサーブレットベースのア
あー、ここ難しかった所です😅
椎葉さんの案をいただきます！

2023-03-13 08:39 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +`WebContext`コンストラクタは、Webベース通信（すなわちリクエストとレスポンス）を表すフィルターで作られた`IWebExchange`抽象オブジェクトに含まれる情報を必要とします。ロケールに何も指定しなければシステムのデフォルトロケールが使用されます（実際のアプリケーションでは絶対に指定した方が良いですが）。
ここも難しかったところです😅
椎葉さんの案をいただきますー

2023-03-14 04:50 UTC, MasatoshiTada commented
- コメントいただいた箇所を修正しました
- whatsnewの方は削除しました（別ブランチに移動済み）

2023-03-14 04:51 UTC, bufferings commented
ありがとうございます！確認しますね。

2023-04-08 04:52 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリは2つの(同じ)バージョンがあります:
スペース残ったままになってます

2023-04-08 07:43 UTC, bufferings requested changes
@MasatoshiTada 修正ありがとうございます！再レビューも遅くなってしまってすみません。
いくつか気づいたところをコメントしました。よろしくお願いします！

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリはに2つの（同じ）バージョンがあります:
[要修正] アスタリスク前後のスペースが残ったままになってます。スペースなしで。

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリはに2つの（同じ）バージョンがあります:
[要修正] 

> このアプリはに2つの（同じ）バージョンがあります:

「はに」になってます。

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリはに2つの（同じ）バージョンがあります:
[要修正] 

> バージョンがあります:

コロンが半角になってます。全角で。

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * アプリケーションオブジェクトは最初に宣言される必要があります（IWebApplicationの実装）。
[好みだけ] 受動態より能動態の方が読みやすいかな

```suggestion
 * 最初にアプリケーションオブジェクト（IWebApplicationの実装）を宣言する必要があります。
```

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * この場合は、Jakartaベースのバージョンが使われています。
[好みだけ] 「will be used」なので「使われています」より「使われます」の方が近いと思う

```suggestion
 * この場合は、Jakartaベースのバージョンが使用されます。
```

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // TemplateEngineオブジェクトがどのように生成・設定されるかは後ほど見ていきます
[要修正] `TemplateEngineオブジェクト` は他と合わせて `テンプレートエンジンオブジェクト` でお願いします。合わせて、ちょっと遠回しだった説明をシンプルにしてみました。

```suggestion
    // テンプレートエンジンオブジェクトの生成と設定については、後ほど見ていきます
```

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 各リクエストは、exchangeオブジェクト（リクエスト、そのレスポンス、およびこの処理に必要なデータ全てを表す）の生成により処理された後、
[確認]

> Each request will be processed by creating an exchange object (modeling
the request, its response and all the data needed for this process) and
then calling the corresponding controller.

「then calling」は「by」の方につながってるんじゃないかな？「エクスチェンジオブジェクトを生成した後にコントローラーを呼び出すことによって、処理されます」の方が意味がつながりそう。

それと

* `exchange` もカタカナ表記にしたほうがよさそう
* コードブロック内の日本語は短めで改行を入れたほうがよさそう

だから、↓こんな感じでどうかな？

> 各リクエストに対して、エクスチェンジオブジェクト（リクエスト、そのレスポンス、および処理に必要な全てのデータを表す）
を生成して、対応するコントローラーを呼び出します。

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +   public void process(
[要修正] このコードブロックは、インデントの空白の数が変？

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +templateEngine.process("home", ctx, writer());
[要修正] writerの括弧は不要です。

2023-04-08 07:43 UTC, bufferings commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +* **\#temporals**：JDK8以上の`java.time`APIの日付/時間オブジェクトを扱います:
[要修正] 細かいですが、最後のコロンが半角です

2023-04-13 08:21 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリはに2つの（同じ）バージョンがあります:
修正しました！

2023-04-13 08:21 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリはに2つの（同じ）バージョンがあります:
「には」に修正しました！

2023-04-13 08:21 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +この章以降で使用しているサンプルのソースコードは *Good Thymes Virtual Grocery (GTVG)* サンプルアプリにあります。このアプリはに2つの（同じ）バージョンがあります:
修正しました！

2023-04-13 08:23 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * アプリケーションオブジェクトは最初に宣言される必要があります（IWebApplicationの実装）。
確かにそうですね。能動態に修正しました！

2023-04-13 08:23 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * この場合は、Jakartaベースのバージョンが使われています。
「使用されます」にしました！

2023-04-13 08:24 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +    // TemplateEngineオブジェクトがどのように生成・設定されるかは後ほど見ていきます
修正しました！

2023-04-13 08:27 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> + * 各リクエストは、exchangeオブジェクト（リクエスト、そのレスポンス、およびこの処理に必要なデータ全てを表す）の生成により処理された後、
> 「then calling」は「by」の方につながってるんじゃないかな？

確かに、その方が自然ですね！修正しました〜

2023-04-13 08:29 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +   public void process(
コピペ時にIntelliJさんが変えちゃったようです💦
スペースの数を英語版と同じに修正しました！

2023-04-13 08:30 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +templateEngine.process("home", ctx, writer());
修正しました！

2023-04-13 08:30 UTC, MasatoshiTada commented on docs/tutorials/3.1/usingthymeleaf_ja.md
> +* **\#temporals**：JDK8以上の`java.time`APIの日付/時間オブジェクトを扱います:
修正しました！

2023-04-15 00:52 UTC, bufferings approved these changes
LGTM :)

2023-04-15 00:53 UTC, merged

2023-04-15 01:08 UTC, bufferings commented
@MasatoshiTada ありがとうございました。docs-ja-masterにマージしました。
usingthymeleafは、僕たちが以前に翻訳したものから3.0の中で更新された部分の取り込みも必要ですね。
（3.0の更新は不要で、3.1の方に変更を反映させたらいいと思います）

これらの修正です。
https://github.com/thymeleaf/thymeleaf-docs/compare/c849d67..master#diff-2f71e53d30e3bc89e89bdaa21928330d893c902e9a2b480ba98fa9dce5316bbd

こちらも別途、対応をお願いできますか？