19 Appendix B: Expression Utility Objects #7
thymeleaf-docs-ja/thymeleaf-docs pull request #8
Opened 2017-04-15 09:42 UTC by bufferings

2017-04-16 10:02 UTC, MasatoshiTada requested changes
ご確認お願いします！
なるべく英語を残さないほうがいいかな〜と思いました。

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * テンプレートのことです。例えば、このコードがルートテンプレートである"A"ではなく、
例えば、このコードがルートテンプレート"A"ではなく、別のテンプレート"B"から"A"に挿入されたフラグメント上にある場合、

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * 元々のテンプレートのことです。例えば、このコードがルートテンプレートである"A"ではなく、
例えば、このコードがルートテンプレート"A"ではなく、別のテンプレート"B"から"A"に挿入されたフラグメント上にある場合、

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * フラグメント識別子としてエスケープ/アンエスケープします
フラグメント識別子(#frag)としてエスケープ/アンエスケープします

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +### 変換
Javadocには「type conversion」と書かれているので、「型変換」の方がより意図が伝わると思います。

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>   * 整数の最小桁数と小数桁数を設定します。
整数部の最小桁数と、小数部の桁数(固定)を設定します。

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>   * 整数の最小桁数と小数桁数と小数点の文字を設定します。
整数部の最小桁数と、小数部の桁数(固定)、小数点の文字を設定します。

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>   * 整数の最小桁数と小数桁数と小数点の文字と千の位の区切り文字を設定します。
整数部の最小桁数と、小数部の桁数(固定)、小数点の文字、千の位の区切り文字を設定します。

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * 整数の最小桁数と、小数桁数を設定します。
整数部の最小桁数と、小数部の桁数(固定)を設定します。

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>   * 部分文字列関係
部分文字列関連の処理

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * appendとprepend
先頭への追加と末尾への追加

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * splitとjoin
分割と結合

2017-04-16 10:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> + * trim
先頭と末尾から空白を除去

2017-04-16 13:10 UTC, bufferings commented
レビューありがとうございます！修正しました。おかげで読みやすくなったと思います！

2017-04-17 11:41 UTC, MasatoshiTada approved these changes

2017-04-17 11:42 UTC, merged