Finish translation for ch.01( #6 )
thymeleaf-docs-ja/thymeleaf-docs pull request #9
Opened 2017-04-15 11:38 UTC by MasatoshiTada

#6

2017-04-16 03:01 UTC, bufferings commented
一旦レビュー終わりました！コメントを確認してくださいー。

2017-04-16 03:01 UTC, bufferings requested changes
一旦レビュー終わりました！コメントを確認してくださいー。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、Web・スタンドアロンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストすらも処理できます。
「Web」は「ウェブ」に統一してますー。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、Web・スタンドアロンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストすらも処理できます。
同様に「スタンドアロン」ではなく「スタンドアローン」にしてます。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、ThymeleafはWeb標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全に検証されたテンプレートを作成することができます。
Web標準→ウェブ標準

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、ThymeleafはWeb標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全に検証されたテンプレートを作成することができます。
設計されているので、もし必要なのであれば完全にvalidatingなテンプレートを作成することも可能です。

かなと思うんだけど、validatingなテンプレートって、検証されたテンプレート、なのかなぁ？

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +
```
There are two *markup* template modes (`HTML` and `XML`), three *textual* template 
modes (`TEXT`, `JAVASCRIPT` and `CSS`) and a *no-op* template mode (`RAW`).
```
が抜けてる。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードは、全ての種類のHTML入力で、HTML5、HTML 4、そしてXHTMLを含みます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り出力に尊重されます。
**`HTML`** テンプレートモードでは、全ての種類のHTML入力が可能で、そこにはHTML5、HTML 4、そしてXHTMLが含まれます。

とか

**`HTML`** テンプレートモードでは、HTML5、HTML 4、そしてXHTMLを含む全ての種類のHTML入力が可能です。

くらいでどうでしょう？

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードは、全ての種類のHTML入力で、HTML5、HTML 4、そしてXHTMLを含みます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り出力に尊重されます。
可能な限り尊重されて出力に反映されます。

とか？

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードは、全ての種類のHTML入力で、HTML5、HTML 4、そしてXHTMLを含みます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り出力に尊重されます。
HTMLの入力を受け付けます、も良いかも？と思った。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式 -- 閉じられていないタグが無いこと、クオートされていない属性が無いことなど -- であることが求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
クオート→クォート
にしてます。すみません＞＜

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式 -- 閉じられていないタグが無いこと、クオートされていない属性が無いことなど -- であることが求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
コードは整形式 -- 閉じられていないタグが無いこと、クオートされていない属性が無いことなど -- であることが求められ

↓

コードは整形式であること -- 閉じられていないタグが無いこと、クオートされていない属性が無いことなど -- が求められ

の方がちょびっと読みやすいかなと。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`TEXT`** テンプレートモードは、マークアップ以外の性質のテンプレートに特殊な構文を使用できます。例としては、テキストEメールやテンプレート化されたドキュメンテーションなどがあるでしょう。HTMLまたはXMLも、`TEXT`として処理できることも覚えておいてください。これは、HTMLやXMLをマークアップとして処理しない場合や、タグ、DOCTYPE、コメントなどを、単なるテキストとして
こんな感じ？

**`TEXT`** テンプレートモードでは、マークアップ形式ではないテンプレートに対して特別な構文を使用することができます。そのようなテンプレートの例としては、テキストEメールやテンプレート化されたドキュメンテーションなどがあるでしょう。HTMLやXMLのテンプレートを `TEXT` として処理できることも覚えておいてください。この場合、マークアップとしてパースされずに、全てのタグやDOCTYPE、コメントなどは、単なるテキストとして扱われます。


---
`TEXT` の前後は半角スペースを開けてください。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理します。これは、HTMLファイルと同様にJavaScriptファイル内でモデルデータを使用できることを意味しますが、特殊エスケープや「自然スクリプト」などのJavaScript固有の統合機能を使用することができます。**`JAVASCRIPT`** テンプレートモードは
**`JAVASCRIPT`** テンプレートモードでは、Thymeleafアプリケーション内のJavaScriptファイルを処理することができます。つまりHTMLファイルと同様に、JavaScriptファイル内でもモデルデータを使用できるということです。また、特殊なエスケープや「ナチュラルスクリプティング」などのJavaScript固有の機能もあります。 **`JAVASCRIPT`** テンプレートモードは「テキストの」モードとして考えられるので `TEXT` テンプレートモードと同様の特別な構文を使用します。

こんな感じ？

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに関連するCSSファイルを処理します。`JAVASCRIPT`モードと同様に`CSS`テンプレーモードも「テクスチュアル」モードで、`TEXT`テンプレートモードと同じ特殊な構文を利用します。
**`CSS`** テンプレートモードでは、Thymeleafアプリケーションに含まれているCSSファイルを処理することができます。 `JAVASCRIPT` モードと同様に `CSS` テンプレーモードも「テキストの」モードなので `TEXT` テンプレートモードからきた特別な構文を利用します。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`RAW`** テンプレートモードは、単純にテンプレートを全く処理しません。これは、処理されているテンプレートに変更のないリソース(ファイル、URLレスポンスなど)を挿入するために使用されます。たとえば、HTML形式の外部の制御されていないリソースをアプリケーションテンプレートに含めることができ、これらのリソースに含まれるThymeleafコードが実行されないことを安全に知ることができます。
**`RAW`** テンプレートモードは、単純にテンプレートに対して何も処理をしません。これは、処理中のテンプレートに対して、(ファイルやURLレスポンスなどの)リソースを変更せずにそのまま挿入する際に使用されます。例えば外部にあって自分達の管理下にないHTML形式のリソースを、アプリケーションのテンプレートにインクルードする場合に、Thymeleafのコードが含まれていたとしても実行されないことが分かっているので安心です。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`RAW`** テンプレートモードは、単純にテンプレートを全く処理しません。これは、処理されているテンプレートに変更のないリソース(ファイル、URLレスポンスなど)を挿入するために使用されます。たとえば、HTML形式の外部の制御されていないリソースをアプリケーションテンプレートに含めることができ、これらのリソースに含まれるThymeleafコードが実行されないことを安全に知ることができます。
んー。僕が書いたの、いまいちだな。なんかもうちょっと分かりやすくかけるといいな。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは非常に拡張性の高いテンプレートエンジンです(実際「テンプレートエンジンフレームワーク」と呼んだほうがいいかもしれません)。Thymeleafは、テンプレートの処理方法を細かく定義し、カスタマイズすることができます。
実際「テンプレートエンジンフレームワーク」と呼んだほうがいいかもしれません

→実際「テンプレートエンジンフレームワーク」と呼べるかもしれません

ちょっと英語の方の文章変わってるので。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは非常に拡張性の高いテンプレートエンジンです(実際「テンプレートエンジンフレームワーク」と呼んだほうがいいかもしれません)。Thymeleafは、テンプレートの処理方法を細かく定義し、カスタマイズすることができます。
Thymeleafは、テンプレートの処理方法を細かく定義し、カスタマイズすることができます。

→Thymeleafでは、テンプレートをどのように処理するかという定義やカスタマイズを細かいレベルで行うことができます。

「細かく」が「定義」だけじゃなくて「カスタマイズ」にもかかってそうなので、その両方にかかってることを明示的に書く感じにしてみました。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +タグ、テキスト、コメントまたはプレースホルダー(テンプレートがマークアップでない場合)などのマークアップ成果物に適用されるロジックは「プロセッサー」と呼ばれます。また、プロセッサーの集合 -- 更にいくつか特別な成果物もあるかもしれません -- は、通常 **ダイアレクト** が構成するものです。Thymeleafでは **スタンダードダイアレクト** というそのまますぐに使えるコアライブラリを
プロセッサー→プロセッサ

にしてます。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、Web・スタンドアロンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストすらも処理できます。
そしてプレーンテキストすらも処理できます。
→そしてプレーンテキストも処理することができます。

くらいがやわらかくていいかな。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafのメインゴールは、優雅で保守性が高いテンプレート作成方法を提供することです。これを達成するために、デザインプロトタイプとして使われるテンプレートに影響することなく、テンプレートファイルにロジックを注入する「ナチュラルテンプレート」というコンセプトに基づいています。これにより、デザインのコミュニケーションを改善すると共に、デザインチームと開発チームのギャップを橋渡しします。
Thymeleafのメインゴールは、優雅で保守性の高いテンプレート作成方法を提供することです。これを実現するために「ナチュラルテンプレート」というコンセプトを採用しており、デザインプロトタイプとして使用されているテンプレートに影響することなくロジックを注入することが可能です。これによって、デザインのコミュニケーションが改善され、デザインチームと開発チームの溝を埋めることができます。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、ThymeleafはWeb標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全に検証されたテンプレートを作成することができます。
あぁ。自分は2.x系のときに
「必要に応じて完全にバリデーションされた状態のテンプレートを作成することもできます。」って訳してますね。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +タグ、テキスト、コメントまたはプレースホルダー(テンプレートがマークアップでない場合)などのマークアップ成果物に適用されるロジックは「プロセッサー」と呼ばれます。また、プロセッサーの集合 -- 更にいくつか特別な成果物もあるかもしれません -- は、通常 **ダイアレクト** が構成するものです。Thymeleafでは **スタンダードダイアレクト** というそのまますぐに使えるコアライブラリを
マークアップの生成物(タグやテキストやコメント、またはテンプレートがマークアップではない場合は単なるプレースホルダー)にロジックを適用するものを「プロセッサ」と呼びます。 **ダイアレクト** は通常、一式のプロセッサ -- と、おそらくいくつかの特別な生成物を合わせたもの -- によって構成されます。Thymeleafのコアライブラリでは **スタンダードダイアレクト** というそのまますぐに使えるダイアレクトを提供していて、大半のユーザーにとってはこれで十分です。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +> ダイアレクトは、実際にはプロセッサを持たず他の種類のアーティファクトで完全に構成されることもありますが、プロセッサは間違いなく最も一般的な使用例です。
実際のところ、ダイアレクトにはプロセッサを含んでいなくてもよくて、完全に別の種類の生成物で構成することも可能であることに注意してください。とはいっても、プロセッサが間違いなく最も一般的な使用例です。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  このチュートリアルでカバーしているのはスタンダードダイアレクトです。以降のページで学ぶ全ての属性や文法は特に明記していなくても、このダイアレクトに定義してあります。
このチュートリアルではスタンダードダイアレクトをカバーしています。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  もちろん、ライブラリの拡張機能を利用して独自の処理ロジックを定義したい、など(スタンダードダイアレクトを拡張することも含めて)独自のダイアレクトを作りたい場合があるかもしれません。テンプレートエンジンは複数のダイアレクトを同時に使用できます。
もちろん、ライブラリの高度な機能を利用しながら独自の処理ロジックを定義したい場合には、(スタンダードダイアレクトを拡張することも含めて)独自のダイアレクトを作成することも可能です。Thymeleafでは複数のダイアレクトを同時に使用する設定もできます。

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  > 公式の thymeleaf-spring3 と thymeleaf-spring4 連携パッケージはどちらも「Springスタンダードダイアレクト」と呼ばれるダイアレクトを定義しています。これは、ほぼスタンダードダイアレクトと同じで、そこにSpring Framework用の便利機能を少しだけ適用しています(例えば、Thymeleaf標準のOGNLの代わりにSpring式言語を使用するなど)
少し本文が修正されていますね。こうなるかと思います。
→例えば、 OGNLの代わりにSpring式言語やSpringELを使用するなど

2017-04-16 03:01 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +ブラウザで正しく表示できるだけでなく、(任意ですが)value属性を指定することもできます(この場合の "James Carrot" の部分です)。プロトタイプを静的にブラウザで開いた場合にはこの値が表示され、テンプレートを処理した場合には `${user.name}` の評価結果値で置き換えられます。
空白抜きで
→この場合の"James Carrot"の部分です

2017-04-16 03:15 UTC, bufferings commented
僕が気をつけてる点としては、直訳すると日本語として不自然になってしまう部分をできるだけ日本語として自然になるように頑張ってるって感じです。

例えば、英語だと「もの」が主語になることが多いけど、日本語だとそれを受動態にして主語を省略してみると分かりやすくなるとか。

英語直訳すると、メインの伝えたいことの前に修飾がいっぱいついてしまって分かりづらくなるから、２つの文章に分けてしまうとか。

日本語にすると、複数の意味に取れてしまう語順があって、そういうのはできるだけ誰が読んでも1つの意味に捉えられるように、語順を工夫するとかです。

2017-04-16 06:58 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafのメインゴールは、優雅で保守性が高いテンプレート作成方法を提供することです。これを達成するために、デザインプロトタイプとして使われるテンプレートに影響することなく、テンプレートファイルにロジックを注入する「ナチュラルテンプレート」というコンセプトに基づいています。これにより、デザインのコミュニケーションを改善すると共に、デザインチームと開発チームのギャップを橋渡しします。
なるほど、確かにこちらの方が自然ですね！

2017-04-16 06:59 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、Web・スタンドアロンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストすらも処理できます。
ガッテンです！

2017-04-16 06:59 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、Web・スタンドアロンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストすらも処理できます。
ガッテンです！

2017-04-16 06:59 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、Web・スタンドアロンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストすらも処理できます。
ガッテンです！

2017-04-16 06:59 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、ThymeleafはWeb標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全に検証されたテンプレートを作成することができます。
ガッテンです！

2017-04-16 07:04 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードは、全ての種類のHTML入力で、HTML5、HTML 4、そしてXHTMLを含みます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り出力に尊重されます。
後者でいこうと思います。ありがとうございますー！

2017-04-16 07:05 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードは、全ての種類のHTML入力で、HTML5、HTML 4、そしてXHTMLを含みます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り出力に尊重されます。
そうですね、その方が自然な感じでいいですね！

2017-04-16 07:05 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式 -- 閉じられていないタグが無いこと、クオートされていない属性が無いことなど -- であることが求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
了解です。統一します！

2017-04-16 07:07 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式 -- 閉じられていないタグが無いこと、クオートされていない属性が無いことなど -- であることが求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
そうですね、修正します！

2017-04-16 07:16 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`TEXT`** テンプレートモードは、マークアップ以外の性質のテンプレートに特殊な構文を使用できます。例としては、テキストEメールやテンプレート化されたドキュメンテーションなどがあるでしょう。HTMLまたはXMLも、`TEXT`として処理できることも覚えておいてください。これは、HTMLやXMLをマークアップとして処理しない場合や、タグ、DOCTYPE、コメントなどを、単なるテキストとして
なるほど、こちらのほうが自然かつ入ってる単語が的確ですね。

2017-04-16 07:22 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`TEXT`** テンプレートモードは、マークアップ以外の性質のテンプレートに特殊な構文を使用できます。例としては、テキストEメールやテンプレート化されたドキュメンテーションなどがあるでしょう。HTMLまたはXMLも、`TEXT`として処理できることも覚えておいてください。これは、HTMLやXMLをマークアップとして処理しない場合や、タグ、DOCTYPE、コメントなどを、単なるテキストとして
すいません、TEXTの前後は半角スペース、って下記の認識で合ってます？

誤
```
**`TEXT`** テンプレートモードは...
```

正
```
** `TEXT` ** テンプレートモードは...
```

2017-04-16 07:25 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理します。これは、HTMLファイルと同様にJavaScriptファイル内でモデルデータを使用できることを意味しますが、特殊エスケープや「自然スクリプト」などのJavaScript固有の統合機能を使用することができます。**`JAVASCRIPT`** テンプレートモードは
なるほど、文章を途中で切った方がわかりやすいですね〜

2017-04-16 07:27 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理します。これは、HTMLファイルと同様にJavaScriptファイル内でモデルデータを使用できることを意味しますが、特殊エスケープや「自然スクリプト」などのJavaScript固有の統合機能を使用することができます。**`JAVASCRIPT`** テンプレートモードは
「textual」は「テキストの」に統一します？確かに、自分で訳しててもカタカナで「テクスチュアル」って意味分かりづらいなあと思ってたので。。。

2017-04-16 07:30 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに関連するCSSファイルを処理します。`JAVASCRIPT`モードと同様に`CSS`テンプレーモードも「テクスチュアル」モードで、`TEXT`テンプレートモードと同じ特殊な構文を利用します。
「from」があるから、「TEXTテンプレートモードからきた」の方が適切ですね。直します！
あと、「CSSテンプレーモード」ってTYPOしてたので、直します。恥ずかしい(^^;

2017-04-16 07:33 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは非常に拡張性の高いテンプレートエンジンです(実際「テンプレートエンジンフレームワーク」と呼んだほうがいいかもしれません)。Thymeleafは、テンプレートの処理方法を細かく定義し、カスタマイズすることができます。
確かに、「better」という単語がなくなってるから、より確定的な表現のほうがいいですね！

2017-04-16 07:35 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは非常に拡張性の高いテンプレートエンジンです(実際「テンプレートエンジンフレームワーク」と呼んだほうがいいかもしれません)。Thymeleafは、テンプレートの処理方法を細かく定義し、カスタマイズすることができます。
確かに、「細かく」は両方にかかってる感じですね。

2017-04-16 07:35 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +ブラウザで正しく表示できるだけでなく、(任意ですが)value属性を指定することもできます(この場合の "James Carrot" の部分です)。プロトタイプを静的にブラウザで開いた場合にはこの値が表示され、テンプレートを処理した場合には `${user.name}` の評価結果値で置き換えられます。
了解です！統一します。

2017-04-16 07:36 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  > 公式の thymeleaf-spring3 と thymeleaf-spring4 連携パッケージはどちらも「Springスタンダードダイアレクト」と呼ばれるダイアレクトを定義しています。これは、ほぼスタンダードダイアレクトと同じで、そこにSpring Framework用の便利機能を少しだけ適用しています(例えば、Thymeleaf標準のOGNLの代わりにSpring式言語を使用するなど)
本当だ！ごめんなさい、見落としですね(^^;

2017-04-16 07:51 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`RAW`** テンプレートモードは、単純にテンプレートを全く処理しません。これは、処理されているテンプレートに変更のないリソース(ファイル、URLレスポンスなど)を挿入するために使用されます。たとえば、HTML形式の外部の制御されていないリソースをアプリケーションテンプレートに含めることができ、これらのリソースに含まれるThymeleafコードが実行されないことを安全に知ることができます。
最後の一文が長くて難しいですねー。2文に分けてみたんですが、こんなんどうでしょうか？

例えば、外部にあって自分達の管理下にないHTML形式のリソースを、アプリケーションのテンプレートにインクルードする場合を考えます。この時、外部リソースにThymeleafのコードが含まれていたとしても、そのコードは実行されないことが分かっているので安心です。

2017-04-16 07:56 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +タグ、テキスト、コメントまたはプレースホルダー(テンプレートがマークアップでない場合)などのマークアップ成果物に適用されるロジックは「プロセッサー」と呼ばれます。また、プロセッサーの集合 -- 更にいくつか特別な成果物もあるかもしれません -- は、通常 **ダイアレクト** が構成するものです。Thymeleafでは **スタンダードダイアレクト** というそのまますぐに使えるコアライブラリを
うーむ、確かにこの方が堅苦しくなくて自然ですね！

2017-04-16 07:56 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +> ダイアレクトは、実際にはプロセッサを持たず他の種類のアーティファクトで完全に構成されることもありますが、プロセッサは間違いなく最も一般的な使用例です。
2文に分けたほうがわかりやすいですね！

2017-04-16 07:57 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  このチュートリアルでカバーしているのはスタンダードダイアレクトです。以降のページで学ぶ全ての属性や文法は特に明記していなくても、このダイアレクトに定義してあります。
ストレートでわかりやすいですね！

2017-04-16 08:00 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  もちろん、ライブラリの拡張機能を利用して独自の処理ロジックを定義したい、など(スタンダードダイアレクトを拡張することも含めて)独自のダイアレクトを作りたい場合があるかもしれません。テンプレートエンジンは複数のダイアレクトを同時に使用できます。
こちらのほうがわかりやすいですね！

2017-04-16 08:02 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +
あらら、すいません、忘れてました。。。追加しまーす！

2017-04-16 08:04 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、ThymeleafはWeb標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全に検証されたテンプレートを作成することができます。
「バリデーションされた」で統一します！

2017-04-16 08:38 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
>  このチュートリアルでカバーしているのはスタンダードダイアレクトです。以降のページで学ぶ全ての属性や文法は特に明記していなくても、このダイアレクトに定義してあります。
元々2.x系の部分の訳ですが、本文が少し変わってるのでー。

2017-04-16 08:43 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`RAW`** テンプレートモードは、単純にテンプレートを全く処理しません。これは、処理されているテンプレートに変更のないリソース(ファイル、URLレスポンスなど)を挿入するために使用されます。たとえば、HTML形式の外部の制御されていないリソースをアプリケーションテンプレートに含めることができ、これらのリソースに含まれるThymeleafコードが実行されないことを安全に知ることができます。
あぁ、いいですね！

2017-04-16 08:50 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理します。これは、HTMLファイルと同様にJavaScriptファイル内でモデルデータを使用できることを意味しますが、特殊エスケープや「自然スクリプト」などのJavaScript固有の統合機能を使用することができます。**`JAVASCRIPT`** テンプレートモードは
質問ありがとうございます。

「テキストの」にしようかと思ったんですけど
ただ、別の部分で「文字列の」と翻訳している部分もあって
```
<!--
Note that textual aliases exist for some of these operators: `div` (`/`), `mod` (`%`).
-->
いくつかの演算子には文字列エイリアスもあります: `div` (`/`), `mod` (`%`)
```

どうしようかな？
「テキスト形式」のモード、テキスト形式のエイリアス、みたいに「テキスト形式の」の方がより本文に近いですかね？

2017-04-16 08:53 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`TEXT`** テンプレートモードは、マークアップ以外の性質のテンプレートに特殊な構文を使用できます。例としては、テキストEメールやテンプレート化されたドキュメンテーションなどがあるでしょう。HTMLまたはXMLも、`TEXT`として処理できることも覚えておいてください。これは、HTMLやXMLをマークアップとして処理しない場合や、タグ、DOCTYPE、コメントなどを、単なるテキストとして
いえ、そちらは大丈夫です。これで合ってます。
```
**`TEXT`** テンプレートモードは...
```

スペース入れてほしいのはこの部分です

誤
```
HTMLまたはXMLも、`TEXT`として処理できることも覚えておいてください。
```

正
```
HTMLまたはXMLも、 `TEXT` として処理できることも覚えておいてください。
```

2017-04-16 08:58 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`TEXT`** テンプレートモードは、マークアップ以外の性質のテンプレートに特殊な構文を使用できます。例としては、テキストEメールやテンプレート化されたドキュメンテーションなどがあるでしょう。HTMLまたはXMLも、`TEXT`として処理できることも覚えておいてください。これは、HTMLやXMLをマークアップとして処理しない場合や、タグ、DOCTYPE、コメントなどを、単なるテキストとして
あ、なるほど！了解でございます！

2017-04-16 08:59 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理します。これは、HTMLファイルと同様にJavaScriptファイル内でモデルデータを使用できることを意味しますが、特殊エスケープや「自然スクリプト」などのJavaScript固有の統合機能を使用することができます。**`JAVASCRIPT`** テンプレートモードは
「テキスト形式の」いいですね！この方が本文に近いと思います。

2017-04-16 09:00 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`RAW`** テンプレートモードは、単純にテンプレートを全く処理しません。これは、処理されているテンプレートに変更のないリソース(ファイル、URLレスポンスなど)を挿入するために使用されます。たとえば、HTML形式の外部の制御されていないリソースをアプリケーションテンプレートに含めることができ、これらのリソースに含まれるThymeleafコードが実行されないことを安全に知ることができます。
ありがとうございます！では、これで行きます。

2017-04-22 06:13 UTC, MasatoshiTada commented
レビューありがとうございました！
修正しましたので、再レビューをお願いします〜

2017-04-23 01:18 UTC, bufferings requested changes
だいぶいい感じになりましたね！
細かいことばかりですがいくつかコメントしたのでよろしくお願いしますー。

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、ウェブ・スタンドアローンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストも処理することができます。
自分から言っておいてほんとにすみませんが「そしてプレーンテキストでさえも処理することができます。」の方が読みやすいと思いました。

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafのメインゴールは、優雅で保守性の高いテンプレート作成方法を提供することです。これを実現するために「ナチュラルテンプレート」というコンセプトを採用しており、デザインプロトタイプとして使用されているテンプレートに影響することなく、ロジックを注入することが可能です。これによって、デザインのコミュニケーションが改善され、デザインチームと開発チームの溝を埋めることができます。
少し読点が多い印象があるので「メインゴールは、」と「影響することなく、」と「これによって、」の読点はない方が読みやすいかも？

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、Thymeleafはウェブ標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全にバリデーションされたテンプレートを作成することができます。
ここは「あなたが必要とする」という意味ではなく「もし必要とするならば」という意味だと思います。ですので、
「また、Thymeleafは当初からウェブ標準 -- 特に **HTML5** -- を念頭に置いて設計されているので、もし必要であれば完全にバリデーションされたテンプレートを作成することも可能です。」かなと思います。

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理することができます。つまりHTMLファイルと同様に、JavaScriptファイル内でもモデルデータを使用できるということです。また、特殊エスケープや「ナチュラルスクリプティング」などのJavaScript固有の機能もあります。 **`JAVASCRIPT`** テンプレ
specialは「特殊な」より「特別な」の方が良さそう。
「特殊エスケープ」→「特別なエスケープ」
「特殊な構文」→「特別な構文」

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式であること -- 閉じられていないタグが無いこと、クォートされていない属性が無いことなど -- が求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
HTMLの方と揃えて
「XML入力です」→「XML入力を受け付けます」
かなぁ？

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式であること -- 閉じられていないタグが無いこと、クォートされていない属性が無いことなど -- が求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
「例外をスローします」→「例外を投げます」にしましょうか。

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードでは、HTML5、HTML 4、そしてXHTMLを含む、全ての種類のHTML入力を受け付けます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り尊重されて出力に反映されます。
「xxxテンプレートモードでは」と「xxxテンプレートモードは」の2種類が存在しているので、どちらかに統一した方が良いと思います。（それによって多少文章に変更を加えないといけなくなるかもしれませんが。）

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに含まれているCSSファイルを処理することができます。 `JAVASCRIPT` モードと同様に `CSS` テンプレートモードも「テキスト形式の」モードなので、 `TEXT` テンプレートモードからきた特別な構文を利用します。
「特別な構文」→「特別な処理構文」かな。

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに含まれているCSSファイルを処理することができます。 `JAVASCRIPT` モードと同様に `CSS` テンプレートモードも「テキスト形式の」モードなので、 `TEXT` テンプレートモードからきた特別な構文を利用します。
すみません、自分で言っておいてなんですが。
「`TEXT` テンプレートモードからきた」の部分って違和感あります？
「`TEXT` テンプレートモードからの」の方がいいかな？
何回も頭の中で言ってるうちにわかんなくなってきたｗ

2017-04-23 01:18 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +> 実際のところ、ダイアレクトにはプロセッサを含んでいなくてもよくて、完全に別の種類の生成物で構成することも可能であることに注意してください。とはいっても、プロセッサが間違いなく最も一般的な使用例です。
「注意してください」って強いかな？「留意してください」「覚えておいてください」「知っておいてください」とかの方がいい？

2017-04-23 05:01 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafは、ウェブ・スタンドアローンどちらの環境でも使える、モダンなサーバーサイドJavaテンプレートエンジンです。HTML、XML、JavaScript、CSS、そしてプレーンテキストも処理することができます。
了解です！「でさえも」に修正します。

2017-04-23 05:05 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +また、Thymeleafはウェブ標準 -- 特に **HTML5** -- を念頭に置いて設計されており、あなたが必要とする完全にバリデーションされたテンプレートを作成することができます。
そうですね、「もし〜」の方が適切ですね。修正します！

2017-04-23 05:11 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`HTML`** テンプレートモードでは、HTML5、HTML 4、そしてXHTMLを含む、全ての種類のHTML入力を受け付けます。バリデーションや整形式チェックは行われず、テンプレートのコード/構造は、可能な限り尊重されて出力に反映されます。
「では」に統一します！

2017-04-23 05:12 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式であること -- 閉じられていないタグが無いこと、クォートされていない属性が無いことなど -- が求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
そうですね、そうした方が「〜では」に統一し易いですね〜。直します！

2017-04-23 05:12 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`XML`** テンプレートモードは、XML入力です。この場合、コードは整形式であること -- 閉じられていないタグが無いこと、クォートされていない属性が無いことなど -- が求められ、整形式違反があった場合はパーサーが例外をスローします。DTDやXMLスキーマに対する「バリデーション」は行われないことに注意してください。
了解でございます！

2017-04-23 05:12 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`JAVASCRIPT`** テンプレートモードは、Thymeleafアプリケーション内のJavaScriptファイルを処理することができます。つまりHTMLファイルと同様に、JavaScriptファイル内でもモデルデータを使用できるということです。また、特殊エスケープや「ナチュラルスクリプティング」などのJavaScript固有の機能もあります。 **`JAVASCRIPT`** テンプレ
了解でございます！

2017-04-23 05:12 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに含まれているCSSファイルを処理することができます。 `JAVASCRIPT` モードと同様に `CSS` テンプレートモードも「テキスト形式の」モードなので、 `TEXT` テンプレートモードからきた特別な構文を利用します。
了解です。上記に合わせて統一します！

2017-04-23 05:14 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +> 実際のところ、ダイアレクトにはプロセッサを含んでいなくてもよくて、完全に別の種類の生成物で構成することも可能であることに注意してください。とはいっても、プロセッサが間違いなく最も一般的な使用例です。
「知っておいてください」が柔らかいと思いますので、これで行きます！

2017-04-23 05:15 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに含まれているCSSファイルを処理することができます。 `JAVASCRIPT` モードと同様に `CSS` テンプレートモードも「テキスト形式の」モードなので、 `TEXT` テンプレートモードからきた特別な構文を利用します。
「 `TEXT` テンプレートモード由来の」とかどうでしょう？

2017-04-23 05:58 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafのメインゴールは、優雅で保守性の高いテンプレート作成方法を提供することです。これを実現するために「ナチュラルテンプレート」というコンセプトを採用しており、デザインプロトタイプとして使用されているテンプレートに影響することなく、ロジックを注入することが可能です。これによって、デザインのコミュニケーションが改善され、デザインチームと開発チームの溝を埋めることができます。
「これによって、」は無くてもいい感じはしますね。
「メインゴールは、」と「影響することなく、」の部分は、読点を消すと1文がけっこう長くなるので、あったほうが良いような気がします。

2017-04-23 07:07 UTC, MasatoshiTada commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +**`CSS`** テンプレートモードは、Thymeleafアプリケーションに含まれているCSSファイルを処理することができます。 `JAVASCRIPT` モードと同様に `CSS` テンプレートモードも「テキスト形式の」モードなので、 `TEXT` テンプレートモードからきた特別な構文を利用します。
相談の結果、「from」を無視しても伝えたい意味は変わらないと判断したので、「 *TEXT* テンプレートモードの」で行きます。

2017-04-23 07:20 UTC, MasatoshiTada commented
修正＋コミット＋プッシュしました！ご確認お願いしますm(_ _)m

2017-04-23 08:50 UTC, bufferings commented on docs/tutorials/3.0/usingthymeleaf_ja.md
> +Thymeleafのメインゴールは、優雅で保守性の高いテンプレート作成方法を提供することです。これを実現するために「ナチュラルテンプレート」というコンセプトを採用しており、デザインプロトタイプとして使用されているテンプレートに影響することなく、ロジックを注入することが可能です。これによって、デザインのコミュニケーションが改善され、デザインチームと開発チームの溝を埋めることができます。
了解です！

2017-04-23 08:51 UTC, bufferings approved these changes

2017-04-23 08:51 UTC, merged